---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# yamllint disable rule:truthy
name: Release

on:
  push:
    branches: [main]
    paths:
      - schemas/_sources/**
      - scripts/**
      - justfile
      - flake.nix
      - flake.lock
      - .github/workflows/release.yaml
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - name: Prepare schemas
        run: |
          nix develop -c just prepare
          mkdir -p out/site
          chmod 777 out/site
      - name: Render schemas + HTML site
        uses: docker://ghcr.io/sholdee/crd-schema-publisher:v2026.609.12656@sha256:f1be1370500884688250005661dfc15da2e0663e64bc1804ef9027548cf1c168
        env:
          BASE_PATH: "/k8s-schemas"
        with:
          args: convert -d /github/workspace/out/_clean -o /github/workspace/out/site --render
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: out/site

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5

  status:
    if: ${{ !cancelled() }}
    needs: [build, deploy]
    name: Status
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            exit 1
          fi
          echo "ok"
