---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# yamllint disable rule:truthy
name: Vendir

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - schemas/vendir.yml

jobs:
  sync:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
       !startsWith(github.event.pull_request.title, 'chore(deps): sync resources managed by vendir'))
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref || github.ref }}

      - uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41 # main
      - uses: DeterminateSystems/magic-nix-cache-action@55718cd9ebf1737a061487d5ada21abf31e99a98 # main

      - name: Sync
        run: nix develop -c just sync

      - name: Commit changes to Renovate PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: "chore(deps): sync vendir sources"
          branch: ${{ github.head_ref }}
          file_pattern: |
            schemas/_sources/**
            schemas/vendir.lock.yml

      - name: Create Pull Request (Manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "chore(deps): sync resources managed by vendir"
          commit-message: "chore(deps): sync resources managed by vendir"
          body: Automated sync of resources via Vendir.
          branch: chore/sync-resources
          delete-branch: true
          base: main
